apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb
  namespace: phpmyadmin
spec:
  selector:
    matchLabels:
      app: mariadb
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      containers:
        - name: mariadb
          image: bitnami/mariadb:8.0.37-debian
          ports:
            - containerPort: 3306
          envFrom:
            - configMapRef:
                name: mariadb-config
          resources:
            requests:
              memory: "250Mi"
              cpu: "20m"
            limits:
              memory: "300Mi"
              cpu: "50m"