apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin-service
  namespace: phpmyadmin
spec:
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30457
  selector:
    app: phpmyadmin
  type: NodePort