apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
  namespace: laravel
spec:
  serviceName: "mysql"
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
    
      initContainers:
      - name: cleanup-data
        image: alpine:latest
        command: ["sh", "-c", "rm -rf /var/lib/mysql/*"]
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql

      containers:
      - name: mysql
        image: mysql:latest
        ports:
        - containerPort: 3306
        envFrom:
        - configMapRef:
            name: mysql-config
        resources:
          requests:
            memory: "256Mi"
            cpu: "500m"
            # # nvidia.com/gpu: 1 # Solicitar 1 GPU
          limits:
            memory: "1Gi"
            cpu: "1"
            # nvidia.com/gpu: 1 # Limitar a 1 GPU
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
  volumeClaimTemplates:
  - metadata:
      name: mysql-persistent-storage
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "standard"
      resources:
        requests:
          storage: 1Gi