apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
  namespace: laravel
spec:
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: bitnami/mysql:8.0.37-debian
          ports:
            - containerPort: 3306
          envFrom:
            - configMapRef:
                name: mysql-config
          resources:
            requests:
              memory: "250Mi"
              cpu: "20m"
            limits:
              memory: "300Mi"
              cpu: "50m"
            volumeMounts:
            - name: www
              mountPath: /usr/share/nginx/html
  volumeClaimTemplates:
  - metadata:
      name: www
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "my-storage-class"
      resources:
        requests:
          storage: 1Gi