apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: phpmyadmin-pvc
  namespace: laravel
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 1Gi